### ISSUE TITLE
Reporting "two P39s" when only one

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#153]
On the [16th Lok Sabha page](https://www.wikidata.org/wiki/User:Verification_pages_bot/verification/in/Member_of_the_16th_Lok_Sabha), Kirti Azad is listed as "manually actionable" due to having two P39s:
![ka double p39s](https://user-images.githubusercontent.com/57483/41955127-a26a66c0-79d6-11e8-9924-9973090defc8.png)

However, in Wikidata he only has a single P39:
![ka single p39](https://user-images.githubusercontent.com/57483/41955131-a3830972-79d6-11e8-93d0-dff25790493f.png)

**Comment by chrismytton** [comment]
The error that we were seeing is:

```
I, [2018-07-02T16:18:12.379337 #6]  INFO -- : [d6c30693-0a2c-4dc3-adde-6d7074466567]   Rendered statements/index.json.jbuilder (8794.1ms)
I, [2018-07-02T16:18:12.379529 #6]  INFO -- : [d6c30693-0a2c-4dc3-adde-6d7074466567] Completed 500 Internal Server Error in 8801ms (ActiveRecord: 22.0ms)
F, [2018-07-02T16:18:12.380128 #6] FATAL -- : [d6c30693-0a2c-4dc3-adde-6d7074466567]   
F, [2018-07-02T16:18:12.380170 #6] FATAL -- : [d6c30693-0a2c-4dc3-adde-6d7074466567] ActionView::Template::Error (undefined method `split' for nil:NilClass):
F, [2018-07-02T16:18:12.380269 #6] FATAL -- : [d6c30693-0a2c-4dc3-adde-6d7074466567]     1: json.statements @classifier.to_a,
[d6c30693-0a2c-4dc3-adde-6d7074466567]     2:   :type,
[d6c30693-0a2c-4dc3-adde-6d7074466567]     3:   :transaction_id,
[d6c30693-0a2c-4dc3-adde-6d7074466567]     4:   :person_item,
F, [2018-07-02T16:18:12.380297 #6] FATAL -- : [d6c30693-0a2c-4dc3-adde-6d7074466567]   
F, [2018-07-02T16:18:12.380321 #6] FATAL -- : [d6c30693-0a2c-4dc3-adde-6d7074466567] app/decorators/statement_decorator.rb:95:in `merged_then_deleted'
[d6c30693-0a2c-4dc3-adde-6d7074466567] app/decorators/statement_decorator.rb:99:in `person_matches?'
[d6c30693-0a2c-4dc3-adde-6d7074466567] app/decorators/statement_decorator.rb:20:in `done?'
[d6c30693-0a2c-4dc3-adde-6d7074466567] app/services/statement_classifier.rb:79:in `statement_type'
[d6c30693-0a2c-4dc3-adde-6d7074466567] app/services/statement_classifier.rb:58:in `block (2 levels) in to_a'
[d6c30693-0a2c-4dc3-adde-6d7074466567] app/services/statement_classifier.rb:57:in `tap'
[d6c30693-0a2c-4dc3-adde-6d7074466567] app/services/statement_classifier.rb:57:in `block in to_a'
[d6c30693-0a2c-4dc3-adde-6d7074466567] app/services/statement_classifier.rb:56:in `map'
[d6c30693-0a2c-4dc3-adde-6d7074466567] app/services/statement_classifier.rb:56:in `to_a'
[d6c30693-0a2c-4dc3-adde-6d7074466567] app/views/statements/index.json.jbuilder:1:in `_app_views_statements_index_json_jbuilder___1078384809666427392_69839255835840'
[d6c30693-0a2c-4dc3-adde-6d7074466567] app/controllers/statements_controller.rb:9:in `block (2 levels) in index'
[d6c30693-0a2c-4dc3-adde-6d7074466567] app/controllers/statements_controller.rb:8:in `index'
```

This is, as ever, hard to test/investigate, but from what I can tell this is happening when there is no matching position data being passed into the `StatementDecorator`, so when `StatementDecorator#person_matches?` calls `merged_then_deleted` it's expecting an array back, but gets `nil`.

**Comment by chrismytton** [comment]
This is now live.
