### ISSUE TITLE
Cron job isn't working

### ISSUE THREAD

**Issue by chrismytton** [mysociety/verification-pages#390]
It looks like the cron job is encountering an error and failing to complete.

```
Suggestion store failed: 500 Internal Server Error
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/app/services/load_statements.rb:48:in `rescue in raw_data'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/app/services/load_statements.rb:46:in `raw_data'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/app/services/load_statements.rb:41:in `csv'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/app/services/load_statements.rb:14:in `run'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/app/services/service_base.rb:6:in `run'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/lib/tasks/load.rake:15:in `block (4 levels) in <main>'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation/delegation.rb:41:in `each'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation/delegation.rb:41:in `each'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/lib/tasks/load.rake:14:in `block (3 levels) in <main>'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/railties-5.2.0/lib/rails/command.rb:48:in `invoke'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
bin/rails:9:in `<main>'

Caused by:
RestClient::InternalServerError: 500 Internal Server Error
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient.rb:67:in `get'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/app/services/load_statements.rb:46:in `raw_data'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/app/services/load_statements.rb:41:in `csv'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/app/services/load_statements.rb:14:in `run'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/app/services/service_base.rb:6:in `run'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/lib/tasks/load.rake:15:in `block (4 levels) in <main>'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation/delegation.rb:41:in `each'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation/delegation.rb:41:in `each'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/lib/tasks/load.rake:14:in `block (3 levels) in <main>'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/railties-5.2.0/lib/rails/command.rb:48:in `invoke'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/mnt/nfs/labstore-secondary-tools-project/verification-pages/verification-pages/vendor/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
bin/rails:9:in `<main>'
```

We should figure out why we're getting a 500 error and fix that, but it would also be good to alter the cron job to trap errors like this and continue onto the next page, rather than bailing out.

**Comment by chrismytton** [comment]
I can't track down exactly why this 500 error occurred, I can't reproduce it, but I did get a 503 error from suggestions-store when trying to reproduce. So making the whole thing a bit more robust seems like a sensible first step.

**Comment by chrismytton** [comment]
Pull request to robustify (sp?) the cron job here: https://github.com/mysociety/verification-pages/pull/391
