### ISSUE TITLE
Webpack failing to complie

### ISSUE THREAD

**Issue by gbp** [mysociety/verification-pages#621]
Probably an issue since #608

**Comment by gbp** [comment]
```
ERROR in ./app/javascript/env.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/@babel/traverse/lib/scope/index.js:866:13)
    at BlockScoping.updateScopeInfo (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:364:17)
    at BlockScoping.run (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:70:24)
    at newFn (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/@babel/traverse/lib/context.js:90:19)

ERROR in ./app/javascript/wikiapi.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/@babel/traverse/lib/scope/index.js:866:13)
    at BlockScoping.updateScopeInfo (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:364:17)
    at BlockScoping.run (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:70:24)
    at newFn (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/graeme/Documents/mySociety/democracy/verification-pages/node_modules/@babel/traverse/lib/context.js:90:19)
```
